apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postfacto
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
# needs values that are set in the postfacto-replicated HelmChart CR
spec:
  project: default
  source:
    chart: postfacto-marlin/development/postfacto
    repoURL: registry.shortrib.io
    targetRevision: 0.1.0-SNAPSHOT
    helm:
      values: |
        ingress:
          enabled: true
          annotations:
            kubernetes.io/tls-acme: "true"
            projectcontour.io/websocket-routes: "/"
            ingress.kubernetes.io/force-ssl-redirect: "true"
          hosts:
          - host: postfacto.shortrib.app
            paths:
            - /
          tls:
          - hosts:
            - postfacto.shortrib.app
            secretName: postfacto-cert 
        postgresql:
          auth:
            enablePostgresUser: false
            username: postfacto
            database: postfacto
            existingSecret: postfacto-postgresql
        redis:
          auth:
            existingSecret: postfacto-redis
  destination:
    namespace: postfacto
    server: https://10.24.1.67:6443
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
