apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: preflight-registry-credentials
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    .dockerconfigjson: AgDByFFeeZw1EBqAoSxiUeJ1k7yUaGidcmXMl+8Atplkq/HcCgDp4YJ2ao0EePuZmKx9y++arLkWctiLN7c+Dz9HO/pIPA810if9iHZ8/zpgeoenG/kGgIKoq34K0cKMMQRGEPq4FO7lFrAJPoXOXmX5aQRA+eDXlYxeWESr7zPLzaV9KMrNp3KiPjp7dlg28E5FABX8mWC8s4r341glFY+K+FXfsXSUviAUZnHlj0mFeIsUVk36Ep6i6LKYIimksuzGsOpuFIZgzxodp+d4tthl4y/SWnC639Wp+51pCJU7StqYzKl1E8ddVfAnwdg8l4Qypp5pXM+ckcNc//IXZo7mIsqZja2bfHGR/ZMSR5JIzlj3SA9rsALDUIZhgjIueCOQ9cNkPmp4fKTh2OszJgze95vXzFp4KYyHksb3U1uY7QtEDHUfG77KdqBNyYX6FZlSyxXvi9l0i7c+HGf2ogAY73MqkKBPPTECR6MBQiTIc3IEAPT1Bx7DQoL2TkVRkXleLDdgfIQ8cO0vWeP/z6zAkp9KRFET3JtobP0pvZUogmTuglxPUybSTx4eL18wvHwi10FDqKu/BdVQ6LTpSTmDwbW+wb3564sWXQbNOkJADbq0lk4eiTwSxath7ZhhAuAGgolhY2U4XqbvdkXQUyzppG2MNlz18T98LP9mVb3/16PIafhcHGw81+GqRh8495Je7kFm+MV6W+n3bUz2AYWmIKZT/QkKt2d2GkQWfNMwT/x7vDLOwlbeQQbgCxCAo0mRoj616lrtKojVgE90EzWZZqqqyCpAVVi2/BGT2Gz44QNsFzgd0V+6dfG0iyZckHTNYm3mchUT4GCphXyxDJb8gGmJF1v3Ektfw5MYWFzxjMU46q/EGP6C88XHYj3ZU/t3irJLwmKa6ToWk9PnSp30Y53iu8JthIjRlCm8JcX9lE36+ZxQy34=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: preflight-registry-credentials
      namespace: argocd
    type: kubernetes.io/dockerconfigjson

