apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postfacto
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/crdant/postfacto-argo-application.git
    path: preflights
  destination:
    namespace: postfacto
    server: https://10.24.1.67:6443
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
