apiVersion: batch/v1
kind: Job
metadata:
  name: preflight-check
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      initContainers:
      - name: format-credentials
        image: nixery.dev/shell/jq
        command:
        - bash
        - -c
        - |
          jq -r '.tlsClientConfig.certData | @base64d' /var/run/secrets/argocd.io/cluster/config > /var/run/secrets/postfacto.io/cluster/client.crt
          jq -r '.tlsClientConfig.keyData | @base64d' /var/run/secrets/argocd.io/cluster/config > /var/run/secrets/postfacto.io/cluster/client.key
          jq -r '.tlsClientConfig.caData | @base64d' /var/run/secrets/argocd.io/cluster/config > /var/run/secrets/postfacto.io/cluster/ca.crt
        volumeMounts:
        - mountPath: /var/run/secrets/argocd.io/cluster
          name: argo-cluster-credentials
          readOnly: true
        - mountPath: /var/run/secrets/postfacto.io/cluster
          name: cluster-credentials
      containers:
      - name: check
        image: ghcr.io/crdant/postfacto-argo-application/toolkit-image@sha256:487277df6957c4eb4a77815bb27a5169a1543449c2e8698e844d3983c25456e6
        env:
        - name: HOME
          value: /home/preflight
        command:
        - bash
        - -c 
        - |
          # check preflights, allowing warnings
          EXIT_CODE_PASS=0
          EXIT_CODE_CATCH_ALL=1
          EXIT_CODE_SPEC_ISSUES=2
          EXIT_CODE_FAIL=3
          EXIT_CODE_WARN=4

          helm template oci://registry.shortrib.io/postfacto-marlin/development/postfacto --version 0.1.0-SNAPSHOT \
            | kubectl preflight - --interactive=false --format json \
                --server https://squirrel.lab.shortrib.net:6443 --certificate-authority /var/run/secrets/postfacto.io/cluster/ca.crt \
                --client-certificate /var/run/secrets/postfacto.io/cluster/client.crt --client-key /var/run/secrets/postfacto.io/cluster/client.key
          result=$?

          case $result in
          $EXIT_CODE_WARN)
            echo "Proceeding with warnings..." 
            exit 0
            ;;
          *)
            exit $RESULT
            ;;
          esac
        volumeMounts:
        - mountPath: /home/preflight/.docker
          name: registry-credentials
          readOnly: true
        - mountPath: /home/preflight/.cache
          name: cache
        - mountPath: /var/run/secrets/postfacto.io/cluster
          name: cluster-credentials
        - mountPath: /var/run/manifests/postfacto.io/manifests
          name: manifests
          readOnly: true
      volumes:
      - name: registry-credentials
        secret:
          secretName: preflight-registry-credentials
          items:
          - key: .dockerconfigjson
            path: config.json
      - name: argo-cluster-credentials
        secret:
          secretName: cluster-squirrel.lab.shortrib.net-1535139613
      - name: cluster-credentials
        emptyDir: {}
      - name: cache 
        emptyDir: {}
      - name: manifests
        emptyDir: {}
      restartPolicy: Never
  backoffLimit: 0
