apiVersion: batch/v1
kind: Job
metadata:
  name: preflight-check
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      initContainers:
      - name: format-credentials
        image: nixery.dev/shell/jq
        command:
        - bash
        - -c
        - |
          jq -r '.bearerToken' /var/run/secrets/argocd.io/cluster/config > /var/run/secrets/postfacto.io/cluster/token
          jq -r '.tlsClientConfig.caData | @base64d' /var/run/secrets/argocd.io/cluster/config > /var/run/secrets/postfacto.io/cluster/ca.crt
        volumeMounts:
        - mountPath: /var/run/secrets/argocd.io/cluster
          name: argo-cluster-credentials
          readOnly: true
        - mountPath: /var/run/secrets/postfacto.io/cluster
          name: cluster-credentials
      - name: helm-template
        image: nixery.dev/shell/kubernetes-helm
        env:
        - name: HOME
          value: /home/preflight
        command:
        - bash
        - -c
        - |
          helm template oci://registry.shortrib.io/postfacto-marlin/development/postfacto --version 0.1.0-SNAPSHOT > /var/run/manifests/postfacto.io/manifests/postfacto.yaml
        volumeMounts:
        - mountPath: /home/preflight/.docker
          name: registry-credentials
          readOnly: true
        - mountPath: /var/run/manifests/postfacto.io/manifests
          name: manifests
      containers:
      - name: check
        image: replicated/preflight
        env:
        - name: HOME
          value: /home/preflight
        command:
        - bash
        - -c 
        - |
          cat /var/run/manifests/postfacto.io/manifests/postfacto.yaml | preflight --interactive=false --format json \
            --server https://10.24.1.67:6443 --certificate-authority /var/run/secrets/postfacto.io/cluster/ca.crt \
            --token $(cat /var/run/secrets/postfacto.io/cluster/token) -
        volumeMounts:
        - mountPath: /home/preflight/.docker
          name: registry-credentials
          readOnly: true
        - mountPath: /var/run/secrets/postfacto.io/cluster
          name: cluster-credentials
        - mountPath: /var/run/manifests/postfacto.io/manifests
          name: manifests
          readOnly: true
      volumes:
      - name: registry-credentials
        secret:
          secretName: preflight-registry-credentials
          items:
          - key: .dockerconfigjson
            path: config.json
      - name: argo-cluster-credentials
        secret:
          secretName: cluster-squirrel.lab.shortrib.net-1535139613
      - name: cluster-credentials
        emptyDir: {}
      - name: manifests
        emptyDir: {}
      restartPolicy: Never
  backoffLimit: 0
