apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postfacto-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/crdant/postfacto-argo-application.git
    targetRevision: feature-separate-clusters
    path: secrets
  destination:
    namespace: postfacto
    server: https://10.24.1.67:6443
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
