apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postfacto-parent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/crdant/postfacto-argo-application.git
    targetRevision: feature-separate-clusters
    path: application
  destination:
    namespace: postfacto
    server: https://squirrel.lab.shortrib.net:6443
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
