apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postfacto
  namespace: argocd

# needs values that are set in the postfacto-replicated HelmChart CR
spec:
  project: default
  source:
    chart: postfacto-marlin/development/postfacto
    repoURL: registry.shortrib.io
    targetRevision: 0.1.0-SNAPSHOT
    path: manifests
    helm:
      valueFiles:
      - values.yaml
  destination:
    namespace: postfacto
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
