apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postfacto-postgresql
  namespace: postfacto
spec:
  encryptedData:
    password: AgCfaOI3HNg7WExPHFBMd8353R8jZBvZGBirNtz5FdrfkXAPqODrmVDrFooFnySDRJjE6/D7vzIsfjBfpk6Tq18BQybR3XbRPKPpm+sjS5URknCM0YT6d5bJ0WnhPmF4UWR6r7auz6fa0anb1W3b/KPMMPZTfJxX1hEU1w7gI36pEQ8OxEjMYT7M9hqDAr52epQf2EONWzVmVEm99Mwq3d9LdVhP2nmv2oUlZ+D8tZlX6o9zqG6LhzUdD6Cdz6fyO5sxJlsEUXt0MXkXDGnFldrDV0OUuppGzioil6qgIklBu7HpOLx44N/ci5gSeyJVHISWD0qsk/Sm4NHh9Be8SW7rUYlbgUvTmuGyPdT4WD3Qkq0cnLDJSpPViz6vov7ZvQuTsW533XhpI/76bdbrHo0HDFh3w9z4U6Ur/pNnP+Ghc/J9PpMs113zww0OIz6MME++WIjTjwgLDNOvjAtL+WJbvLVJ3D9XWi6qv4NwMbOPZVVW9F3aUbvXwJU5kpKMv8k1fkkqlx3in7FuXBOo1LRtiu03O2gEPCXjjOUzM6ZxR1iwslvALoLoL8i5F4fJ8VifjOG6Hxi91UC08l/YMfBbjSEQMgx3ffCdHErmT1rofiWY0qP5DTZ0bqgT1PLfQ75MA08PnwraxzillC6FQFFCUclL3irRUGpRv3+Vdl2JEfY6k113DI4/Jvup7abg/uEejd9XtirGHUH9kSbPqWJKhGGIKWhgfoYIJV74j3w=
    postgres-password: AgAud+nmBF2ovXTJeQZ+jn8+1vYtT8FqI8XHc9zhMqA1rsBoYuhJ+PE4QTVVoh1AzjIA9uAy99pGZCUuk+J5WYZ/dG8dntZlbmRL28ZID1ZHfCtxhVqBJcM3Z9Gx8asbyjYk5kO0WLeJubJnblNtcrDkQJj/Y/MQhi/6LjemyQuF+UI7YelNiS5ZNYvBqr9ReaBiaeTifgT4nAHs79D9vs6hGuaQEc1XWkSdftDx/Gp8XfxPQf/i+aFgn5PsHAwvmUUUbpIdS2sV9A0oTtopGud9YrH/ve9dxgEPhOLvtASvXe+deWNOUT9Geabn2mgNdrJTW/h21pvv5Pzu+yUp5mcANXPQxsDO8t9m5PBqMDvy8dZbEgmQwa5L5xf7nMaHYW8BfRtHpp8tYhlA8Q6fNIBGcuZYc82D0/8a8YHOszfDdAhGgk1yLxaNAvm4Z7j7NKYY5a3Om199zHCf6nhpqn3tBLK6hU+V48UqAVfHbnnLeyyDV5buDnUIi7CNep4ElBn/ZVcPCiASULG0sWzV/vntV/1HpOeI1CCTXuq+SVJHqkKGUkxwnHFepwFAtFK7gJaQISdtVKcKjP53NBu+k235BCGStJJvGvNMXBXDlIs3ib2wux6fBv7cVuqe2qYAe/FfHfI16gUdI/zNFRImivBZyTHlbneJqhplE3NytDyidhNGLNXjcBT0ajHvoeSoIDd6dsMy00skgaFSadZN76QTZeNBOadIPcP00bfj0kF8
  template:
    metadata:
      name: postfacto-postgresql
      namespace: postfacto

