apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: argocd-preflight-check
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: preflight-checks
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  verbs:
  - list
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
- apiGroups: 
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: argocd:argocd-preflight-check:preflight-checks
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: preflight-checks
subjects:
- kind: ServiceAccount
  name: argocd-preflight-check
  namespace: argocd
