apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postfacto-postgresql
  namespace: postfacto
spec:
  encryptedData:
    password: AgCC+DMIcjHaFURfy2jl5WV+GwIudlmdmqnwJhdaUnVovWm1kydX+qobC/72ZfTsuz/mQxfQF8eXf7sFFSalhl5oSGJL9uHBtPFplYw6mhEiCVvvFzwslsYoBnKnK7Zliozr5/z7ALxQNf+LFCaQNGDzDRjUL5uKKU+Wz1bv1g7jfylLmm79io4uHvn0CPYZ6PRMwSBEdzrI7oYq+aRyniUk8GFbhkPW3fS9BTaD6BnkPfLLuUjg9zhojwEsHxa8AdDts4mWAMO1hk4espTewjhkM9Rvp8/uJyEChe7vER2XmKXsk+CP6fGECvdWlsKl8bp46QB/9WutgyPs5Vc8QlFoJpEcU1TBTDT/BJOdWk5dxwln3WJj6D1jTXreKBzZ+wQwvaA75rIxfcdATwfltkvmEtZq+fm7FRW8Kzu1If/nBHwloEG2lMhEaF3gJzJF5h0rnXNYpcsisybTfQOtIyLd+WZIfvgKG0CnSZM9Nuex0AFS0wayTCf4iS82IwnU2ppvTYD/4YDXRkWjw/2coEFJXcKuz/wYbOL/zH5/OkDEkTupMcXkMsxSuAqkXkRALCcd9RWTE2Y7iA/PQ04fMt1fnaiJDIJEBFVVGU8I1tUEzB5BQxRq08I57CS6vyodwWyV0twde9rZWiLWwtpKd1KjpNNuH58hlH7kPTetQIdbPjsyNqz/e2PEALynFQodI24PeDxYsyDEUadR+GT4KL+t0cfXJFjrLjNw9F/bYY0H9ux28SePNbvLpSbjPA==
    postgressPassword: AgBwYGQY/36cbRY5RS0Wj8F+PT65+iEbsZCERPuyCZFijrngiTt808eYsWHaUg6jivuvxfpCke+FLkQgE+d7R/s5cibeQrDlbEz0SjYLJBCF2KW6AQcT5LEJB4AQCZcYY3jshnwFIdmsCuosLquNf6DGxzPn9k1kW1KtEC+rE0hE31eRgGvUAyt90zMIyDybQsUNJM7aNaAEI3muAZlhrnrxqUBpRjuPbQ62kebEMwzdRP4F1/w2XFgM8a5NMp35MPb61xVrfxtgR67qYEh4GyaOpMnXilneG/0ZC2ctKH2Z1A38B8bwclqkF2BWmXB67AIcz3lVNuPI+cD+DrMOaWgDgx9Rga/cHHNFK2cVQ+7tOnkPt76cyZ7hG+/a2DZW1HXPP3tWq/5bZw6oERL0TWrP8p5wQCXQEUjCj996XOYuURh213rMybUISFhH8tthkD2hPr2/wVnBoQw9O08Z/1sPCxUOgr1lBtDyen8Z/fyUaf28Ke9arXeI3JPPJ4E9DH89JUV/O5VCUDVYUP9B/7mx29ALfMgO9qe4csFZL2vhKIwmWBhkZv6931TL3ROFdZNV7pwLJ2nkk3w0o8DvJ2bopDM/lHu1IQzC9I1/WVOYpcK0MRqSW1ILfetnFznUy6KSuX9c8AHHwRe5TzRUdEoqSZh8JPRCzYBOKVcsYSpa0U6OV+L8rtAEpC/IV783DT4ECKJ8UMOEG8C8ihHmJbJi28BUNxMbA+epKsHw4k6UnKpkdmpsEw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postfacto-postgresql
      namespace: postfacto

