apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postfacto-postgresql
  namespace: postfacto
spec:
  encryptedData:
    password: AgAPOizGbXgjKDD1Ka5xxg9N2YSJPyeGj4nhAmHJd8JBCqVE0mKqFRvX5sEcbnomdhPE3hwUAi8Ju/LMK59MDmdd1ZyH+RaJSki+4A16bhFKNoZQ6NDa8d+o0LWrIUqO4hc+/r+vzk6hNcP0uEsnjVKcFxyD7p2t7WHleCAXzlWEzgElK2uGusvU198u5ErU5ZOS3YrISYbpgsz9Y/FJxpmiz8ymXqKCIc0zalT4x8ErCQhAe3l6HEjpb+CLjYvTwaPQNAQLER2S0XleRb9IyOyxcdOH35iFcHHvXSv6/V7BYbXKkinHWTDplUAscx4I9ZX/V8wYsHfsQIHqUe0lbibj6OwFfQVz55MUa7HfXWQwlKBpsBZkjCnKL++A5TETYnOVUPSkPSpTMNnhDUEUtiNDlN2wL81r75DeegZpS36OIwR4RQeMkBTK4eem19QENdEDoXXcikX99pcg23V8Oqb0Y6mkH1NSZ8x3V2X6CtrpuX5lekhu5HIwOQsw73nEN4ZNP6A5AGLKG2C9hkiTC7KRcIX7AwDqb+xSY/PmDOmY4Fkjx1vTnjW7yHwvsomDYYAzFava65JG/XUplLmUZ9RaO21WpBRJm/6rpaPejqD3ww85tlSonSzNRgg5tL5VfnWgmuhKV2CIsK/MOg1AAMZXozRLbiKxQdkcmynH1hWAMsJQdXZCW9GfPlOf7HaZYm/Gqgb3knbrfx9QkPaEnDBKxWluyGNN6IzUTju/9MXt
    postgres-password: AgBY4jQsGwCRH8FwrdshlxSIJuu0SNtNyidKZljjiCAacDLqPZVYA2mgbmCgO2c0e8yWWx9PgIUsSEf903BHjYiptikRkJ5sKUU00c9Capb0da9gWuj4x+YwhT8BfuSmeN5QAiKzrq3Li6DZZjRFAi+oCZ1JAnvq3mnWLkdYn9a6vz2GpjqkENaIKU+QNyyI+GBDKw+zh8O8sZWlom43na4gYkWAkwVRzD3ccGnPYCB7jvN/uhpf28CxN4APAhhxn71sHVC3ilj6++WrpYKgakLp1aiQS6SGTeTOLdYII0eJ8MsvdmUF0iSFTm1yiMzxylgHcQF2gT9fBi3R9m4419HJD3VF4rqQ8WpzkdtX8n8je6G6rleKQI05w/yY/uj2KJRW0d59+eBGj84g15TaSH+FUGoj86LJVUrqlPmNW5uPlwYsq2rc7qjmh+Or6SKt3qJkObk4K+L5uLk3SFnoCskONnEG136O5oF6vgNHurGexhJGu9TWiOMeYhhLfvnoUV5GLGS0YP9UfqV9aNVUJxmCepTa8wbMRDL+0Uy2A+SuZQ280HKYAfYAbvDjY1GomTiBc404a38y/dAjePpak7InVZ92lnakz8H/8kECARKLm4E5sepXF5GSs0vGfFhFJ8j0mtEp/Ixymo87UuXdpYNnGMSG2vZhzXLqXO0CNYvU+YzpdTjZ0Ud6uMk+PpZfbUGSWmQjqcGZaMuSIx6hl4+x1Njs/Mo9Opu56GIl
  template:
    metadata:
      creationTimestamp: null
      name: postfacto-postgresql
      namespace: postfacto

